### ISSUE TITLE
libpthread.so.0: version `GLIBC_PRIVATE' not found (required by .../metanorma-linux-x86_64)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/homebrew-metanorma#85]
https://github.com/metanorma/homebrew-metanorma/actions/runs/4393526308/jobs/7693982990#step:9:170

```
...
/home/linuxbrew/.linuxbrew/Cellar/metanorma/1.6.14_1/bin/metanorma-linux-x86_64: /lib/x86_64-linux-gnu/libpthread.so.0: version `GLIBC_PRIVATE' not found (required by /home/linuxbrew/.linuxbrew/Cellar/metanorma/1.6.14_1/bin/metanorma-linux-x86_64)
Error: metanorma/metanorma/metanorma: failed
An exception occurred within a child process:
  BuildError: Failed executing: /home/linuxbrew/.linuxbrew/Cellar/metanorma/1.6.14_1/bin/metanorma --type iso /tmp/metanorma-test-20230311-48713-1tztw0o/test-iso.adoc --agree-to-terms
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2538:in `block in system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2474:in `open'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2474:in `system'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/metanorma/homebrew-metanorma/Formula/metanorma.rb:109:in `block in <class:Metanorma>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2313:in `block (3 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/extend/kernel.rb:521:in `with_env'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2312:in `block (2 levels) in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:968:in `with_logging'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2311:in `block in run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/mktemp.rb:77:in `run'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2589:in `mktemp'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/formula.rb:2305:in `run_test'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:44:in `block in <main>'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/home/linuxbrew/.linuxbrew/Homebrew/Library/Homebrew/test.rb:48:in `<main>'
...
```

**Comment by CAMOBAP** [comment]
@maxirmx just in case you have any thoughts on this or can point to some direction to investigate (I don't want you to investigate)

**Comment by maxirmx** [comment]
No, I did not see such message before

**Comment by maxirmx** [comment]
This is fixed by https://github.com/tamatebako/tebako/issues/98
